
1. Función que retorne los indices de la triangular superior de una matriz de tamaño n x n.


In [1]:
import numpy as np

In [39]:
def indices_triangularsup(n): #n = orden de la matriz cuadrada
  
  ord = 0.5*n*(n-1)+n  #calculo el tamaño necesario de los vectores de acuerdo a la cantidad de elementos de la triangular superior
  ind_f = np.zeros(int(ord), dtype=np.uint8)  #vector indice por fila de ceros de tamaño: 0.5*n*(n-1)+n
  ind_c = np.zeros(int(ord),dtype=np.uint8)  #vector indice por fila de ceros de tamaño: 0.5*n*(n-1)+n    

  cont = 0               
  for f in range(n):   # filas
 
    for c in range(n): # columnas
     if f <= c:        #cada vez que la columna sea mayor a la fila
       ind_f[cont]=f   # agregar f en la posicion cont del vector
       ind_c[cont]=c   # agregar c en la posicion cont del vector
       cont=cont+1     #sumo 1 al contador para pasar a la siguiente posicion del vector
    
    

 
  return ind_f,ind_c


In [42]:
i = 1
while i==1:
  n = int(input("introduzca el orden de la matriz: "))
  if n<0:
    print("el orden de la matriz debe ser un numero entero positivo")
  else: i=0 


introduzca el orden de la matriz: 6


In [43]:
indices_triangularsup(n) #llamo la funcion para una matriz de orden n

(array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 4, 4, 5],
       dtype=uint8),
 array([0, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 2, 3, 4, 5, 3, 4, 5, 4, 5, 5],
       dtype=uint8))

In [44]:
M = np.empty(shape=(n,n), dtype=np.uint8) #Matriz aleatoria
M

array([[160,  40, 140, 114, 228,  85],
       [  0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0]], dtype=uint8)

In [45]:
M[indices_triangularsup(n)] #elementos de la matriz correspondientes a los indices retornados por la funcion

array([160,  40, 140, 114, 228,  85,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0], dtype=uint8)